#!/usr/bin/env python3

from pathlib import Path
import re


ROOT_DIR = Path(__file__).resolve().parent.parent
INDEX_PATH = ROOT_DIR / "index.html"
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}


def natural_sort_key(value):
    return [
        int(part) if part.isdigit() else part.lower()
        for part in re.split(r"(\d+)", value)
    ]


def get_image_files():
    return sorted(
        [
            path.name
            for path in ROOT_DIR.iterdir()
            if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
        ],
        key=natural_sort_key,
    )


def read_existing_gallery(html):
    match = re.search(r"const filenames = \[\r?\n([\s\S]*?)\r?\n    \];", html)

    if not match:
        raise RuntimeError("Could not find the `const filenames = [...]` gallery list in index.html.")

    active = []
    excluded = []

    for line in match.group(1).splitlines():
        active_match = re.match(r"""\s*['"]([^'"]+)['"],?\s*$""", line)
        excluded_match = re.match(r"""\s*//\s*['"]([^'"]+)['"],?\s*$""", line)

        if active_match:
            active.append(active_match.group(1))
        elif excluded_match:
            excluded.append(excluded_match.group(1))

    return {
        "block": match.group(0),
        "active": active,
        "excluded": excluded,
    }


def build_gallery_block(active, excluded):
    lines = [
        "const filenames = [",
        "      // Generated by scripts/update-gallery.py",
        *[f"      '{filename}'," for filename in active],
    ]

    if excluded:
        lines.extend(["", "      // Excluded from gallery:"])
        lines.extend(f"      // '{filename}'," for filename in excluded)

    lines.append("    ];")
    return "\n".join(lines)


def main():
    html = INDEX_PATH.read_text(encoding="utf-8")
    gallery = read_existing_gallery(html)
    image_files = get_image_files()
    known_files = set(gallery["active"]) | set(gallery["excluded"])
    new_images = [filename for filename in image_files if filename not in known_files]
    active = [*gallery["active"], *new_images]
    next_block = build_gallery_block(active, gallery["excluded"])

    if next_block == gallery["block"]:
        print("Gallery is already up to date.")
        return

    INDEX_PATH.write_text(html.replace(gallery["block"], next_block), encoding="utf-8")

    if not new_images:
        print("Regenerated gallery list; no new images were found.")
    else:
        print(f"Added {len(new_images)} image(s) to the gallery:")
        for filename in new_images:
            print(f"- {filename}")


if __name__ == "__main__":
    main()
